version: 1.1.{build}

branches:
  only:
    - bleeding
    - master

build:
  project: DotPDF
  publish_nuget: true

image: Visual Studio 2017

configuration: Release

deploy:
  provider: NuGet
  api_key:
    secure: qHc8xMpwgrrxm3ZYOxDdhspKbfFI/HqgZUM9grSqWBaePRs1zAH002NBZFMOBuo6

before_build:
  - nuget restore
