version: 1.1.{build}

configuration: Release

branches:
  only:
    - bleeding
    - master

build:
  project: DotPDF
  verbosity: minimal

image: Visual Studio 2017

before_build:
  - nuget restore

deploy:
  provider: NuGet
  api_key:
    secure: wfa9m2doR4fOORf5Bi+9hQC5irxYSFhM2VhpWkINwmY1ANAsNF9AVkJP4+Se/qGJ
  skip_symbols: true
  artifact: /.*\.nupkg/
